Repository MSU-AI/clash-royale-gym, pull requests merged in 2024-03, with the labels that each got.

#10 Release: Added pyproject.toml
  pyproject.toml
Labels: codebase quality, needs-review

#13 removed vscode and setup
  .gitignore
  .vscode/settings.json
  setup.py
Labels: approved

#15 Fix: Changed requires-python
  .vscode/settings.json
  pyproject.toml
Labels: bug, dependencies, needs-review

#16 Fix: Package
  clash_royale/__init__.py
  clash_royale/envs/clash_royale_env.py
  clash_royale/envs/game_engine/__init__.py
  pyproject.toml
Labels: bug, dependencies

#22 Add: Game engine
  .gitignore
  CHANGES.md
  clash_royale/envs/clash_royale_env.py
  clash_royale/envs/game_engine/__init__.py
  clash_royale/envs/game_engine/arena.py
  clash_royale/envs/game_engine/entities/__init__.py
  clash_royale/envs/game_engine/entities/entity.py
  clash_royale/envs/game_engine/entities/logic_entity.py
  clash_royale/envs/game_engine/game_engine.py
  clash_royale/envs/game_engine/logic/__init.py
  clash_royale/envs/game_engine/logic/attack.py
  clash_royale/envs/game_engine/logic/movement.py
  clash_royale/envs/game_engine/logic/target.py
  clash_royale/envs/game_engine/player.py
  clash_royale/envs/game_engine/struct.py
  clash_royale/envs/game_engine/utils.py
Labels: needs-review

#24 Feature: Entity attack scheduling
  clash_royale/envs/game_engine/arena.py
  clash_royale/envs/game_engine/entities/entity.py
  clash_royale/envs/game_engine/entities/logic_entity.py
  clash_royale/envs/game_engine/logic/attack.py
  clash_royale/envs/game_engine/logic/movement.py
  clash_royale/envs/game_engine/logic/target.py
  clash_royale/envs/game_engine/struct.py
Labels: codebase quality, feature request, needs-review

#29 Fixing pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, codebase quality

#30 Feature: Add implementation and document of Class Player
  clash_royale/envs/game_engine/card.py
  clash_royale/envs/game_engine/player.py
Labels: needs-review

#27 Add documentation to README
  README.md
Labels: needs-review, documentation

#23 Codebase: Create pylint.yml for Python Linting
  .github/workflows/pylint.yml
Labels: feature request

#32 Added some dependencies
  pyproject.toml
Labels: bug, dependencies

#41 Codebase Quality: Fixed various issues with code documentation and formatting.
  .github/workflows/pylint.yml
  CHANGES.md
  clash_royale/envs/clash_royale_env.py
  clash_royale/envs/game_engine/arena.py
  clash_royale/envs/game_engine/card.py
  clash_royale/envs/game_engine/entities/__init__.py
  clash_royale/envs/game_engine/entities/entity.py
  clash_royale/envs/game_engine/entities/logic_entity.py
  clash_royale/envs/game_engine/game_engine.py
  clash_royale/envs/game_engine/logic/__init__.py
  clash_royale/envs/game_engine/logic/attack.py
  clash_royale/envs/game_engine/logic/movement.py
  clash_royale/envs/game_engine/logic/target.py
  clash_royale/envs/game_engine/player.py
  clash_royale/envs/game_engine/struct.py
  clash_royale/envs/game_engine/utils.py
Labels: bug, crash, dependencies, feature request, help wanted, needs-review, documentation
